<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYRk19AC\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYRk19AC/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYRk19AC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYRk19AC\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYRk19AC\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YRk19AC',
    'container.build_id' => 'c24395c1',
    'container.build_time' => 1641557251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYRk19AC');
